### ISSUE TITLE
A Bug in running process

### ISSUE THREAD

**Issue by YoungBigBird1985** [bzGeng/TPEM#2]
USE_CUDA: True
Traceback (most recent call last):
  File "./run_TPEM.py", line 12, in <module>
    full_path = check_resume_folder(args["path"])
  File "/home/peng/TPEM-master/utils/__init__.py", line 95, in check_resume_folder
    path_with_epoch = str(path) + '/EPOCH' + str(resume_from_epoch)
UnboundLocalError: local variable 'resume_from_epoch' referenced before assignment

**Comment by bzGeng** [comment]
![image](https://user-images.githubusercontent.com/71705336/131425599-ef954324-ee2a-45d5-b9c4-9fa3bba8e0a9.png)
It seems that there's no legal checkpoint under path. If there's no checkpoint under path or it's epoch > 50, If you make sure there's checkpoint under your setting path, further check if it's epoch>50. You can just change the range to a bigger one like 200.

**Comment by YoungBigBird1985** [comment]
Hi authors,

Many thanks for your prompt reply. I found out that an error happened before this issue:

Traceback (most recent call last):
  File "./run_TPEM.py", line 102, in <module>
    training_process(model)
  File "./run_TPEM.py", line 89, in training_process
    acc, _, _ = model.evaluate(dev, avg_best, epoch + 1)
  File "/home/peng/TPEM-master/models/TPEM.py", line 559, in evaluate
    bleu_score = moses_multi_bleu(np.array(hyp), np.array(ref), lowercase=True)
  File "/home/peng/TPEM-master/utils/measures.py", line 105, in moses_multi_bleu
    bleu_out = subprocess.check_output(bleu_cmd, stdin=read_pred, stderr=subprocess.STDOUT)
  File "/home/peng/.conda/envs/TPEM/lib/python3.7/subprocess.py", line 411, in check_output
    **kwargs).stdout
  File "/home/peng/.conda/envs/TPEM/lib/python3.7/subprocess.py", line 488, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/home/peng/.conda/envs/TPEM/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/peng/.conda/envs/TPEM/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
PermissionError: [Errno 13] Permission denied: './utils/multi-bleu.perl'

**Comment by YoungBigBird1985** [comment]
I add the executable permission to 'utils/multi-bleu.perl', the code can work.

**Comment by bzGeng** [comment]
You are welcome, hope you enjoy it !
